---
# file: roles/vagrant-ansible-init/tasks/configure-hosts.yml

#- name: "Append host ip adresses to list"
#  set_fact:
#    host_ips: "{{ host_ips }} + [ '{{ item.value.ansible_host }} {{ item.key }}' ]"
#  loop: "{{ lookup('dict', hostvars) }}"
#  loop_control:
#    label: "{{ item.value.ansible_host }} {{ item.key }} "
#  tags:
#    - configure

- name: "Append host ip adresses to list"
  set_fact:
    host_ips: "{{ host_ips }} + [ '{{ item.value.ansible_host }} {{ item.key }}' ]"
  no_log: true
  with_dict: "{{ hostvars }}"
  tags:
    - configure

- name: "Write host entries in /etc/hosts"
  lineinfile:
    path: /etc/hosts
    state: present
    regexp: "^{{ item }}$"
    line: "{{ item }}"
    backup: yes
  loop: "{{ host_ips|flatten(levels=1) }}"
  tags:
    - configure
