---
# file: roles/vagrant-ansible-init/tasks/main.yml

- name: "Define ansible_config."
  set_fact:
    ansible_config: "{{ __ansible_config | list }}"
  when: ansible_config is not defined

- name: Configure Ansible
  ansible.builtin.include_tasks: configure-ansible.yml

- name: Install dependencies
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  with_first_found:
    - files:
        - "setup-{{ ansible_distribution }}.yml"
        - "setup-{{ ansible_os_family }}.yml"
      skip: True

- name: Configure SSH keys
  ansible.builtin.include_tasks: configure-ssh-keys.yml
