---
# file: roles/vagrant-ansible-init/tasks/main.yml

- name: "Define ansible_config."
  set_fact:
    ansible_config: "{{ __ansible_config | list }}"
  when: ansible_config is not defined

- name: Configure Ansible
  ansible.builtin.include_tasks: configure-ansible.yml

- name: Configure SSH keys
  ansible.builtin.include_tasks: configure-ssh-keys.yml
