---
# file: roles/vagrant-ansible-init/tasks/main.yml

- name: "Define ansible_config."
  set_fact:
    ansible_config: "{{ __ansible_config | list }}"
  when: ansible_config is not defined

# Configure Ansible
- include_tasks: configure-ansible.yml

# Configure SSH keys
- include_tasks: configure-ssh-keys.yml
